import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StoreWrapper from "@/redux/store/StoreWrapper/StoreWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const circularStdBold = localFont({
  src: "../assets/fonts/circular-std-font-family/CircularStd-Bold.ttf",
});
const circularStdMedium = localFont({
  src: "../assets/fonts/circular-std-font-family/CircularStd-Medium.ttf",
});

export const metadata: Metadata = {
  title: "Logoipsum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${circularStdMedium.className} ${circularStdBold.className}`}
      >
        <StoreWrapper>
          <Header />
          {children}
          <ToastContainer />
        </StoreWrapper>
      </body>
    </html>
  );
}
